#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Numerex.Resource", IsApplication=true)]

namespace Numerex
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050051
			public const int Button_Ajuda = 2131034193;
			
			// aapt resource value: 0x7f050052
			public const int Button_Opcoes = 2131034194;
			
			// aapt resource value: 0x7f050050
			public const int Button_Play = 2131034192;
			
			// aapt resource value: 0x7f050000
			public const int base_0x0 = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int base_0x1 = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int base_0x2 = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int base_0x3 = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int base_0x4 = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int base_1x0 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int base_1x1 = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int base_1x2 = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int base_1x3 = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int base_1x4 = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int btn_0x0 = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int btn_0x1 = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int btn_0x2 = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int btn_0x3 = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int btn_0x4 = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int btn_0x5 = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int btn_0x6 = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int btn_0x7 = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int btn_0x8 = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int btn_0x9 = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int btn_1x0 = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int btn_1x1 = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int btn_1x2 = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int btn_1x3 = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int btn_1x4 = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int btn_1x5 = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int btn_1x6 = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int btn_1x7 = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int btn_1x8 = 2131034140;
			
			// aapt resource value: 0x7f05001d
			public const int btn_1x9 = 2131034141;
			
			// aapt resource value: 0x7f05001e
			public const int btn_2x0 = 2131034142;
			
			// aapt resource value: 0x7f05001f
			public const int btn_2x1 = 2131034143;
			
			// aapt resource value: 0x7f050020
			public const int btn_2x2 = 2131034144;
			
			// aapt resource value: 0x7f050021
			public const int btn_2x3 = 2131034145;
			
			// aapt resource value: 0x7f050022
			public const int btn_2x4 = 2131034146;
			
			// aapt resource value: 0x7f050023
			public const int btn_2x5 = 2131034147;
			
			// aapt resource value: 0x7f050024
			public const int btn_2x6 = 2131034148;
			
			// aapt resource value: 0x7f050025
			public const int btn_2x7 = 2131034149;
			
			// aapt resource value: 0x7f050026
			public const int btn_2x8 = 2131034150;
			
			// aapt resource value: 0x7f050027
			public const int btn_2x9 = 2131034151;
			
			// aapt resource value: 0x7f050028
			public const int btn_3x0 = 2131034152;
			
			// aapt resource value: 0x7f050029
			public const int btn_3x1 = 2131034153;
			
			// aapt resource value: 0x7f05002a
			public const int btn_3x2 = 2131034154;
			
			// aapt resource value: 0x7f05002b
			public const int btn_3x3 = 2131034155;
			
			// aapt resource value: 0x7f05002c
			public const int btn_3x4 = 2131034156;
			
			// aapt resource value: 0x7f05002d
			public const int btn_3x5 = 2131034157;
			
			// aapt resource value: 0x7f05002e
			public const int btn_3x6 = 2131034158;
			
			// aapt resource value: 0x7f05002f
			public const int btn_3x7 = 2131034159;
			
			// aapt resource value: 0x7f050030
			public const int btn_3x8 = 2131034160;
			
			// aapt resource value: 0x7f050031
			public const int btn_3x9 = 2131034161;
			
			// aapt resource value: 0x7f050032
			public const int btn_4x0 = 2131034162;
			
			// aapt resource value: 0x7f050033
			public const int btn_4x1 = 2131034163;
			
			// aapt resource value: 0x7f050034
			public const int btn_4x2 = 2131034164;
			
			// aapt resource value: 0x7f050035
			public const int btn_4x3 = 2131034165;
			
			// aapt resource value: 0x7f050036
			public const int btn_4x4 = 2131034166;
			
			// aapt resource value: 0x7f050037
			public const int btn_4x5 = 2131034167;
			
			// aapt resource value: 0x7f050038
			public const int btn_4x6 = 2131034168;
			
			// aapt resource value: 0x7f050039
			public const int btn_4x7 = 2131034169;
			
			// aapt resource value: 0x7f05003a
			public const int btn_4x8 = 2131034170;
			
			// aapt resource value: 0x7f05003b
			public const int btn_4x9 = 2131034171;
			
			// aapt resource value: 0x7f05003c
			public const int btn_5x0 = 2131034172;
			
			// aapt resource value: 0x7f05003d
			public const int btn_5x1 = 2131034173;
			
			// aapt resource value: 0x7f05003e
			public const int btn_5x2 = 2131034174;
			
			// aapt resource value: 0x7f05003f
			public const int btn_5x3 = 2131034175;
			
			// aapt resource value: 0x7f050040
			public const int btn_5x4 = 2131034176;
			
			// aapt resource value: 0x7f050041
			public const int btn_5x5 = 2131034177;
			
			// aapt resource value: 0x7f050042
			public const int btn_5x6 = 2131034178;
			
			// aapt resource value: 0x7f050043
			public const int btn_5x7 = 2131034179;
			
			// aapt resource value: 0x7f050044
			public const int btn_5x8 = 2131034180;
			
			// aapt resource value: 0x7f050045
			public const int btn_5x9 = 2131034181;
			
			// aapt resource value: 0x7f050046
			public const int btn_6x0 = 2131034182;
			
			// aapt resource value: 0x7f050047
			public const int btn_6x1 = 2131034183;
			
			// aapt resource value: 0x7f050048
			public const int btn_6x2 = 2131034184;
			
			// aapt resource value: 0x7f050049
			public const int btn_6x3 = 2131034185;
			
			// aapt resource value: 0x7f05004a
			public const int btn_6x4 = 2131034186;
			
			// aapt resource value: 0x7f05004b
			public const int btn_6x5 = 2131034187;
			
			// aapt resource value: 0x7f05004c
			public const int btn_6x6 = 2131034188;
			
			// aapt resource value: 0x7f05004d
			public const int btn_6x7 = 2131034189;
			
			// aapt resource value: 0x7f05004e
			public const int btn_6x8 = 2131034190;
			
			// aapt resource value: 0x7f05004f
			public const int btn_6x9 = 2131034191;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Game_Screen = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
